import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { computeMfcc, MFCC_COEFFS } from '../src/main/pipeline/mfcc'

interface Fixture {
  sampleRate: number
  winlen: number
  winstep: number
  pcm: number[]
  mfcc: number[][]
}

// Generated by scripts/export-asd-onnx.py with python_speech_features — the
// library the LR-ASD model was trained with. The TS implementation must match
// it closely or the active-speaker scores degrade silently.
const fixture: Fixture = JSON.parse(
  readFileSync(join(__dirname, 'fixtures', 'mfcc-fixture.json'), 'utf-8')
)

describe('computeMfcc', () => {
  it('matches python_speech_features on the fixture signal', () => {
    const pcm = Int16Array.from(fixture.pcm)
    const { features, frames } = computeMfcc(
      pcm,
      fixture.sampleRate,
      fixture.winlen,
      fixture.winstep
    )
    expect(frames).toBe(fixture.mfcc.length)
    let worst = 0
    for (let f = 0; f < frames; f++) {
      for (let c = 0; c < MFCC_COEFFS; c++) {
        const got = features[f * MFCC_COEFFS + c]
        const want = fixture.mfcc[f][c]
        worst = Math.max(worst, Math.abs(got - want))
      }
    }
    // float32 storage + fp reassociation; features are O(1..100) in magnitude.
    expect(worst).toBeLessThan(1e-3)
  })

  it('produces ~100 frames per second at the ASD window settings', () => {
    const pcm = new Int16Array(16000 * 2) // 2s of silence
    const { frames } = computeMfcc(pcm, 16000)
    expect(frames).toBe(1 + Math.ceil((pcm.length - 400) / 160))
  })
})
